services:
   orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order.Api/Dockerfile
    depends_on:
      - mssql
      - rabbitmq

   workerservice:
    image: ${DOCKER_REGISTRY-}workerservice
    build:
      context: .
      dockerfile: WorkerService/Dockerfile
    depends_on:
      - mssql
      - rabbitmq

   rabbitmq:
    image: rabbitmq:3.12.2-management
   mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
   kafka:
    image: confluentinc/cp-kafka:7.6.0
   kafka-ui:
    container_name: kafka-ui
   redis:
    image: redis:7.2-alpine
    container_name: redis
  

volumes:
  mssql_data:
  kafka_data:
  redis_data: